#!/usr/bin/env bash

# Check for the correct amount of arguments
if [ -z "$1" ] || [ -n "$2" ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit 1
fi

# Execute the command line arguments
if [ "$1" == "start" ]; then
  ./manage_my_process &
  echo $$ > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$1" == "stop" ]; then
  if [ -e "/var/run/my_process.pid" ]; then
    pkill -F /var/run/my_process.pid && rm /var/run/my_process.pid
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running"
  fi

elif [ "$1" == "restart" ]; then
  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"
else
  echo "Usage: manage_my_process {start|stop|restart}"
  exit 1
fi
